insert into Gang values (default, 'Vagos', 'YELLOW');
insert into Gang values (default, 'Ballas', 'PURPLE');
insert into Gang values (default, 'Families', 'GREEN');
insert into Gang values (default, 'Bloods', 'RED');

insert into AreaUnit values (default,0,0);
insert into AreaUnit values (default,0,1);
insert into AreaUnit values (default,0,2);
insert into AreaUnit values (default,0,3);
insert into AreaUnit values (default,0,4);
insert into AreaUnit values (default,0,5);
insert into AreaUnit values (default,0,6);
insert into AreaUnit values (default,0,7);
insert into AreaUnit values (default,1,0);
insert into AreaUnit values (default,1,1);
insert into AreaUnit values (default,1,2);
insert into AreaUnit values (default,1,3);
insert into AreaUnit values (default,1,4);
insert into AreaUnit values (default,1,5);
insert into AreaUnit values (default,1,6);
insert into AreaUnit values (default,1,7);
insert into AreaUnit values (default,2,0);
insert into AreaUnit values (default,2,1);
insert into AreaUnit values (default,2,2);
insert into AreaUnit values (default,2,3);
insert into AreaUnit values (default,2,4);
insert into AreaUnit values (default,2,5);
insert into AreaUnit values (default,2,6);
insert into AreaUnit values (default,2,7);
insert into AreaUnit values (default,3,0);
insert into AreaUnit values (default,3,1);
insert into AreaUnit values (default,3,2);
insert into AreaUnit values (default,3,3);
insert into AreaUnit values (default,3,4);
insert into AreaUnit values (default,3,5);
insert into AreaUnit values (default,3,6);
insert into AreaUnit values (default,3,7);
insert into AreaUnit values (default,4,0);
insert into AreaUnit values (default,4,1);
insert into AreaUnit values (default,4,2);
insert into AreaUnit values (default,4,3);
insert into AreaUnit values (default,4,4);
insert into AreaUnit values (default,4,5);
insert into AreaUnit values (default,4,6);
insert into AreaUnit values (default,4,7);
insert into AreaUnit values (default,5,0);
insert into AreaUnit values (default,5,1);
insert into AreaUnit values (default,5,2);
insert into AreaUnit values (default,5,3);
insert into AreaUnit values (default,5,4);
insert into AreaUnit values (default,5,5);
insert into AreaUnit values (default,5,6);
insert into AreaUnit values (default,5,7);
insert into AreaUnit values (default,6,0);
insert into AreaUnit values (default,6,1);
insert into AreaUnit values (default,6,2);
insert into AreaUnit values (default,6,3);
insert into AreaUnit values (default,6,4);
insert into AreaUnit values (default,6,5);
insert into AreaUnit values (default,6,6);
insert into AreaUnit values (default,6,7);
insert into AreaUnit values (default,7,0);
insert into AreaUnit values (default,7,1);
insert into AreaUnit values (default,7,2);
insert into AreaUnit values (default,7,3);
insert into AreaUnit values (default,7,4);
insert into AreaUnit values (default,7,5);
insert into AreaUnit values (default,7,6);
insert into AreaUnit values (default,7,7);


insert into Block values (1,10, true, 1);
insert into Block values (2,10, false,1);
insert into Block values (3,10, false,1);
insert into Block values (4,10, false,1);
insert into Block values (5,10, false,2);
insert into Block values (6,10, false,2);
insert into Block values (7,10, false,2);
insert into Block values (8,10, true, 2);
insert into Block values (9,10, false);
insert into Block values (10,10, false);
insert into Block values (11,10, false);
insert into Block values (12,10, false);
insert into Block values (13,10, false);
insert into Block values (14,10, false);
insert into Block values (15,10, false);
insert into Block values (16,10, false);
insert into Block values (17,10, false);
insert into Block values (18,10, false);
insert into Block values (19,10, false);
insert into Block values (20,10, false);
insert into Block values (21,10, false);
insert into Block values (22,10, false);
insert into Block values (23,10, false);
insert into Block values (24,10, false);
insert into Block values (25,10, false);
insert into Block values (26,10, false);
insert into Block values (27,10, false);
insert into Block values (28,10, false);
insert into Block values (29,10, false);
insert into Block values (30,10, false);
insert into Block values (31,10, false);
insert into Block values (32,10, false);
insert into Block values (33,10, false);
insert into Block values (34,10, false);
insert into Block values (35,10, false);
insert into Block values (36,10, false);
insert into Block values (37,10, false);
insert into Block values (38,10, false);
insert into Block values (39,10, false);
insert into Block values (40,10, false);
insert into Block values (41,10, false);
insert into Block values (42,10, false);
insert into Block values (43,10, false);
insert into Block values (44,10, false);
insert into Block values (45,10, false);
insert into Block values (46,10, false);
insert into Block values (47,10, false);
insert into Block values (48,10, false);
insert into Block values (49,10, false);
insert into Block values (50,10, false);
insert into Block values (51,10, false);
insert into Block values (52,10, false);
insert into Block values (53,10, false);
insert into Block values (54,10, false);
insert into Block values (55,10, false);
insert into Block values (56,10, false);
insert into Block values (57,10, true, 3);
insert into Block values (58,10, false);
insert into Block values (59,10, false);
insert into Block values (60,10, false);
insert into Block values (61,10, false);
insert into Block values (62,10, false);
insert into Block values (63,10, false);
insert into Block values (64,10, true, 4);

insert into Workshop values (1, 'Vagos custom');
insert into Workshop values (8, 'Ballas custom');
insert into Workshop values (57, 'Families custom');
insert into Workshop values (64, 'Bloods custom');

insert into Bandit values (default, 'Roberto', 'Babreno',21 ,1, '00:00:00');
insert into Bandit values (default, 'Bebra', NULL, 34 ,1, '00:00:00');
insert into Bandit values (default, 'Michael', NULL, 12 , 2,  '00:00:00');
insert into Bandit values (default, 'Mike', NULL , 45 ,2,  '00:00:00');
insert into Bandit values (default, 'Bill', NULL , 19 , 3, '00:00:00');
insert into Bandit values (default, 'Frachesko', NULL , 81, 3,  '00:00:00');
insert into Bandit values (default, 'Nick', NULL, 61, 4, '00:00:00');
insert into Bandit values (default, 'Nickolas', NULL, 17, 4, '00:00:00');

insert into ItemType values (default,  'HEAL' , 'Аптечка');
insert into ItemType values (default, 'PROTECT' , 'Грузовик');
insert into ItemType values (default,  'DAMAGE' , 'Пистолет');

insert into Item values (default, 'кольт', 10 ,3, NULL);
insert into Item values (default, 'кольт', 10, 3, NULL);
insert into Item values (default, 'кольт', 10, 3, NULL);
insert into Item values (default, 'кольт', 10 ,3, NULL);
insert into Item values (default, 'кольт', 10 ,3, NULL);
insert into Item values (default, 'кольт', 10 ,3, NULL);
insert into Item values (default, 'кольт', 10, 3, NULL);
insert into Item values (default, 'кольт', 10, 3, NULL);
insert into Item values (default, 'камаз', 2 ,2, NULL);
insert into Item values (default, 'камаз', 2 ,2, NULL);
insert into Item values (default, 'камаз', 2 ,2, NULL);
insert into Item values (default, 'камаз', 2 ,2, NULL);
insert into Item values (default, 'камаз', 2 ,2, NULL);
insert into Item values (default, 'камаз', 2 ,2, NULL);
insert into Item values (default, 'камаз', 2 ,2, NULL);
insert into Item values (default, 'камаз', 2 ,2, NULL);
insert into Item values (default, 'малая аптечка', 2 ,1, NULL);
insert into Item values (default, 'малая аптечка', 2 ,1, NULL);
insert into Item values (default, 'малая аптечка', 2 ,1, NULL);
insert into Item values (default, 'малая аптечка', 2 ,1, NULL);
insert into Item values (default, 'малая аптечка', 2 ,1, NULL);
insert into Item values (default, 'малая аптечка', 2 ,1, NULL);
insert into Item values (default, 'малая аптечка', 2 ,1, NULL);
insert into Item values (default, 'малая аптечка', 2 ,1, NULL);

insert into Inventory values (1,1);
insert into Inventory values (2,2);
insert into Inventory values (3,3);
insert into Inventory values (4,4);
insert into Inventory values (5,5);
insert into Inventory values (6,6);
insert into Inventory values (7,7);
insert into Inventory values (8,8);
insert into Inventory values (1,9);
insert into Inventory values (2,10);
insert into Inventory values (3,11);
insert into Inventory values (4,12);
insert into Inventory values (5,13);
insert into Inventory values (6,14);
insert into Inventory values (7,15);
insert into Inventory values (8,16);
insert into Inventory values (1,17);
insert into Inventory values (2,18);
insert into Inventory values (3,19);
insert into Inventory values (4,20);
insert into Inventory values (5,21);
insert into Inventory values (6,22);
insert into Inventory values (7,23);
insert into Inventory values (8,24);

insert into Accommodation values (default, 4,1, now());
insert into Accommodation values (default, 1,2, now());
insert into Accommodation values (default, 5,3, now());
insert into Accommodation values (default, 8,4, now());
insert into Accommodation values (default, 57,5, now());
insert into Accommodation values (default, 57,6, now());
insert into Accommodation values (default, 64,7, now());
insert into Accommodation values (default, 64,8, now());