insert into "Банда" values (1, 'Vagos', 'YELLOW');
insert into "Банда" values (2, 'Ballas', 'PURPLE');
insert into "Банда" values (3, 'Families', 'GREEN');
insert into "Банда" values (4, 'Bloods', 'RED');

insert into "ЕдиницаТерритории" values (1,0,0);
insert into "ЕдиницаТерритории" values (2,0,1);
insert into "ЕдиницаТерритории" values (3,0,2);
insert into "ЕдиницаТерритории" values (4,0,3);
insert into "ЕдиницаТерритории" values (5,0,4);
insert into "ЕдиницаТерритории" values (6,0,5);
insert into "ЕдиницаТерритории" values (7,0,6);
insert into "ЕдиницаТерритории" values (8,0,7);
insert into "ЕдиницаТерритории" values (9,1,0);
insert into "ЕдиницаТерритории" values (10,1,1);
insert into "ЕдиницаТерритории" values (11,1,2);
insert into "ЕдиницаТерритории" values (12,1,3);
insert into "ЕдиницаТерритории" values (13,1,4);
insert into "ЕдиницаТерритории" values (14,1,5);
insert into "ЕдиницаТерритории" values (15,1,6);
insert into "ЕдиницаТерритории" values (16,1,7);
insert into "ЕдиницаТерритории" values (17,2,0);
insert into "ЕдиницаТерритории" values (18,2,1);
insert into "ЕдиницаТерритории" values (19,2,2);
insert into "ЕдиницаТерритории" values (20,2,3);
insert into "ЕдиницаТерритории" values (21,2,4);
insert into "ЕдиницаТерритории" values (22,2,5);
insert into "ЕдиницаТерритории" values (23,2,6);
insert into "ЕдиницаТерритории" values (24,2,7);
insert into "ЕдиницаТерритории" values (25,3,0);
insert into "ЕдиницаТерритории" values (26,3,1);
insert into "ЕдиницаТерритории" values (27,3,2);
insert into "ЕдиницаТерритории" values (28,3,3);
insert into "ЕдиницаТерритории" values (29,3,4);
insert into "ЕдиницаТерритории" values (30,3,5);
insert into "ЕдиницаТерритории" values (31,3,6);
insert into "ЕдиницаТерритории" values (32,3,7);
insert into "ЕдиницаТерритории" values (33,4,0);
insert into "ЕдиницаТерритории" values (34,4,1);
insert into "ЕдиницаТерритории" values (35,4,2);
insert into "ЕдиницаТерритории" values (36,4,3);
insert into "ЕдиницаТерритории" values (37,4,4);
insert into "ЕдиницаТерритории" values (38,4,5);
insert into "ЕдиницаТерритории" values (39,4,6);
insert into "ЕдиницаТерритории" values (40,4,7);
insert into "ЕдиницаТерритории" values (41,5,0);
insert into "ЕдиницаТерритории" values (42,5,1);
insert into "ЕдиницаТерритории" values (43,5,2);
insert into "ЕдиницаТерритории" values (44,5,3);
insert into "ЕдиницаТерритории" values (45,5,4);
insert into "ЕдиницаТерритории" values (46,5,5);
insert into "ЕдиницаТерритории" values (47,5,6);
insert into "ЕдиницаТерритории" values (48,5,7);
insert into "ЕдиницаТерритории" values (49,6,0);
insert into "ЕдиницаТерритории" values (50,6,1);
insert into "ЕдиницаТерритории" values (51,6,2);
insert into "ЕдиницаТерритории" values (52,6,3);
insert into "ЕдиницаТерритории" values (53,6,4);
insert into "ЕдиницаТерритории" values (54,6,5);
insert into "ЕдиницаТерритории" values (55,6,6);
insert into "ЕдиницаТерритории" values (56,6,7);
insert into "ЕдиницаТерритории" values (57,7,0);
insert into "ЕдиницаТерритории" values (58,7,1);
insert into "ЕдиницаТерритории" values (59,7,2);
insert into "ЕдиницаТерритории" values (60,7,3);
insert into "ЕдиницаТерритории" values (61,7,4);
insert into "ЕдиницаТерритории" values (62,7,5);
insert into "ЕдиницаТерритории" values (63,7,6);
insert into "ЕдиницаТерритории" values (64,7,7);


insert into "Блок" values (1,10, true, 1);
insert into "Блок" values (2,10, false,1);
insert into "Блок" values (3,10, false,1);
insert into "Блок" values (4,10, false,1);
insert into "Блок" values (5,10, false,2);
insert into "Блок" values (6,10, false,2);
insert into "Блок" values (7,10, false,2);
insert into "Блок" values (8,10, true, 2);
insert into "Блок" values (9,10, false);
insert into "Блок" values (10,10, false);
insert into "Блок" values (11,10, false);
insert into "Блок" values (12,10, false);
insert into "Блок" values (13,10, false);
insert into "Блок" values (14,10, false);
insert into "Блок" values (15,10, false);
insert into "Блок" values (16,10, false);
insert into "Блок" values (17,10, false);
insert into "Блок" values (18,10, false);
insert into "Блок" values (19,10, false);
insert into "Блок" values (20,10, false);
insert into "Блок" values (21,10, false);
insert into "Блок" values (22,10, false);
insert into "Блок" values (23,10, false);
insert into "Блок" values (24,10, false);
insert into "Блок" values (25,10, false);
insert into "Блок" values (26,10, false);
insert into "Блок" values (27,10, false);
insert into "Блок" values (28,10, false);
insert into "Блок" values (29,10, false);
insert into "Блок" values (30,10, false);
insert into "Блок" values (31,10, false);
insert into "Блок" values (32,10, false);
insert into "Блок" values (33,10, false);
insert into "Блок" values (34,10, false);
insert into "Блок" values (35,10, false);
insert into "Блок" values (36,10, false);
insert into "Блок" values (37,10, false);
insert into "Блок" values (38,10, false);
insert into "Блок" values (39,10, false);
insert into "Блок" values (40,10, false);
insert into "Блок" values (41,10, false);
insert into "Блок" values (42,10, false);
insert into "Блок" values (43,10, false);
insert into "Блок" values (44,10, false);
insert into "Блок" values (45,10, false);
insert into "Блок" values (46,10, false);
insert into "Блок" values (47,10, false);
insert into "Блок" values (48,10, false);
insert into "Блок" values (49,10, false);
insert into "Блок" values (50,10, false);
insert into "Блок" values (51,10, false);
insert into "Блок" values (52,10, false);
insert into "Блок" values (53,10, false);
insert into "Блок" values (54,10, false);
insert into "Блок" values (55,10, false);
insert into "Блок" values (56,10, false);
insert into "Блок" values (57,10, true, 3);
insert into "Блок" values (58,10, false);
insert into "Блок" values (59,10, false);
insert into "Блок" values (60,10, false);
insert into "Блок" values (61,10, false);
insert into "Блок" values (62,10, false);
insert into "Блок" values (63,10, false);
insert into "Блок" values (64,10, true, 4);

insert into "Мастерская" values (1, 'Vagos custom');
insert into "Мастерская" values (8, 'Ballas custom');
insert into "Мастерская" values (57, 'Families custom');
insert into "Мастерская" values (64, 'Bloods custom');

insert into "Бандит" values (1, 'Roberto', 'Babreno',21 ,1, '00:00:00');
insert into "Бандит" values (2, 'Bebra', NULL, 34 ,1, '00:00:00');
insert into "Бандит" values (3, 'Michael', NULL, 12 , 2,  '00:00:00');
insert into "Бандит" values (4, 'Mike', NULL , 45 ,2,  '00:00:00');
insert into "Бандит" values (5, 'Bill', NULL , 19 , 3, '00:00:00');
insert into "Бандит" values (6, 'Frachesko', NULL , 81, 3,  '00:00:00');
insert into "Бандит" values (7, 'Nick', NULL, 61, 4, '00:00:00');
insert into "Бандит" values (8, 'Nickolas', NULL, 17, 4, '00:00:00');

insert into "ТипПредмета" values (1,  'HEAL' , 'Аптечка');
insert into "ТипПредмета" values (2, 'PROTECT' , 'Грузовик');
insert into "ТипПредмета" values (3,  'DAMAGE' , 'Пистолет');

insert into "Предмет" values (1, 'кольт', 10 ,3, NULL);
insert into "Предмет" values (default, 'кольт', 10, 3, NULL);
insert into "Предмет" values (default, 'кольт', 10, 3, NULL);
insert into "Предмет" values (default, 'кольт', 10 ,3, NULL);
insert into "Предмет" values (default, 'кольт', 10 ,3, NULL);
insert into "Предмет" values (default, 'кольт', 10 ,3, NULL);
insert into "Предмет" values (default, 'кольт', 10, 3, NULL);
insert into "Предмет" values (default, 'кольт', 10, 3, NULL);
insert into "Предмет" values (default, 'камаз', 2 ,2, NULL);
insert into "Предмет" values (default, 'камаз', 2 ,2, NULL);
insert into "Предмет" values (default, 'камаз', 2 ,2, NULL);
insert into "Предмет" values (default, 'камаз', 2 ,2, NULL);
insert into "Предмет" values (default, 'камаз', 2 ,2, NULL);
insert into "Предмет" values (default, 'камаз', 2 ,2, NULL);
insert into "Предмет" values (default, 'камаз', 2 ,2, NULL);
insert into "Предмет" values (default, 'камаз', 2 ,2, NULL);
insert into "Предмет" values (default, 'малая аптечка', 2 ,1, NULL);
insert into "Предмет" values (default, 'малая аптечка', 2 ,1, NULL);
insert into "Предмет" values (default, 'малая аптечка', 2 ,1, NULL);
insert into "Предмет" values (default, 'малая аптечка', 2 ,1, NULL);
insert into "Предмет" values (default, 'малая аптечка', 2 ,1, NULL);
insert into "Предмет" values (default, 'малая аптечка', 2 ,1, NULL);
insert into "Предмет" values (default, 'малая аптечка', 2 ,1, NULL);
insert into "Предмет" values (default, 'малая аптечка', 2 ,1, NULL);

insert into "Инвентарь" values (1,1);
insert into "Инвентарь" values (2,2);
insert into "Инвентарь" values (3,3);
insert into "Инвентарь" values (4,4);
insert into "Инвентарь" values (5,5);
insert into "Инвентарь" values (6,6);
insert into "Инвентарь" values (7,7);
insert into "Инвентарь" values (8,8);
insert into "Инвентарь" values (1,9);
insert into "Инвентарь" values (2,10);
insert into "Инвентарь" values (3,11);
insert into "Инвентарь" values (4,12);
insert into "Инвентарь" values (5,13);
insert into "Инвентарь" values (6,14);
insert into "Инвентарь" values (7,15);
insert into "Инвентарь" values (8,16);
insert into "Инвентарь" values (1,17);
insert into "Инвентарь" values (2,18);
insert into "Инвентарь" values (3,19);
insert into "Инвентарь" values (4,20);
insert into "Инвентарь" values (5,21);
insert into "Инвентарь" values (6,22);
insert into "Инвентарь" values (7,23);
insert into "Инвентарь" values (8,24);

insert into "Проживание" values (default, 4,1, now());
insert into "Проживание" values (default, 1,2, now());
insert into "Проживание" values (default, 5,3, now());
insert into "Проживание" values (default, 8,4, now());
insert into "Проживание" values (default, 57,5, now());
insert into "Проживание" values (default, 57,6, now());
insert into "Проживание" values (default, 64,7, now());
insert into "Проживание" values (default, 64,8, now());